# Use a base image
FROM alpine:latest

# Set a default value for the environment variable
ENV MY_ENV_VAR=default_value

# Print the environment variable
CMD echo "The value of MY_ENV_VAR is: $MY_ENV_VAR"
